"""Add is_tenant_admin_flag to user model

Revision ID: 115fcece56ce
Revises: 333c4f1190fd
Create Date: 2026-02-09 21:52:35.429983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115fcece56ce'
down_revision = '333c4f1190fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_tenant_admin_flag', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_tenant_admin_flag')

    # ### end Alembic commands ###
