"""Add tenant_id to order_item, payment, inventory

Revision ID: 196b9c8b2843
Revises: 2443d86d94f1
Create Date: 2026-02-08 22:01:26.210223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '196b9c8b2843'
down_revision = '2443d86d94f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_order_item_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.alter_column('provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('reference',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_payment_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenant', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payment_tenant_id'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('reference',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_order_item_tenant_id'))
        batch_op.alter_column('variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
