"""Adjusted base model

Revision ID: 2443d86d94f1
Revises: bd80143c356f
Create Date: 2026-02-01 23:47:37.578420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2443d86d94f1'
down_revision = 'bd80143c356f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_product_variant_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_variant_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variant_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_product_variant_product_id'))
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
