"""Add is_tenant_admin to User

Revision ID: 333c4f1190fd
Revises: bf36346ba75a
Create Date: 2026-02-09 21:33:48.350207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333c4f1190fd'
down_revision = 'bf36346ba75a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_tenant_admin_flag', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_tenant_admin_flag')

    # ### end Alembic commands ###
