"""Add tenant-scoping to product and product_variant models

Revision ID: 39559303c4a4
Revises: 1a715d976b0b
Create Date: 2026-02-12 19:40:38.256450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39559303c4a4'
down_revision = '1a715d976b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('product_slug_key'), type_='unique')
        batch_op.create_unique_constraint('uq_product_tenant_slug', ['tenant_id', 'slug'])

    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('product_variant_sku_key'), type_='unique')
        batch_op.create_unique_constraint('uq_variant_tenant_sku', ['tenant_id', 'sku'])
        batch_op.create_foreign_key(None, 'tenant', ['tenant_id'], ['id'])
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_variant_tenant_sku', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('product_variant_sku_key'), ['sku'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('image')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('uq_product_tenant_slug', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('product_slug_key'), ['slug'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
