"""Add upgraded tenant and tenant_banner models

Revision ID: 3e1835f9436f
Revises: e2088c7ccd81
Create Date: 2026-02-14 06:10:20.232358

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e1835f9436f'
down_revision = 'e2088c7ccd81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_banner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_banner',
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('background_image', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hover_effect', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subtitle', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('image_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('image_alt', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cta_text', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cta_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bg_color', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('text_color', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tenant_banner_pkey'))
    )
    # ### end Alembic commands ###
