"""Add image_file to tenant_banner models

Revision ID: 4dc2e3861df9
Revises: 8adf14234939
Create Date: 2026-02-14 07:59:50.204003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc2e3861df9'
down_revision = '8adf14234939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_banner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=255), nullable=False))
        batch_op.drop_column('image_alt')
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_banner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('image_alt', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
