"""Fix tenant and tenant_banner models

Revision ID: 8adf14234939
Revises: 3e1835f9436f
Create Date: 2026-02-14 06:30:56.985837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8adf14234939'
down_revision = '3e1835f9436f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_banner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_banner_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenant', ['tenant_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_banner', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tenant_banner_tenant_id'))

    # ### end Alembic commands ###
