"""Add is_tenant_admin_flag

Revision ID: bcd2b9ad074b
Revises: 115fcece56ce
Create Date: 2026-02-10 21:34:55.004638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcd2b9ad074b'
down_revision = '115fcece56ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_tenant_admin_flag', 
                sa.Boolean(), 
                nullable=False,
                server_default=sa.false(),
            )
        )

    # 2. Remove server default (ORM handles defaults going forward)
    with op.batch_alter_table("user") as batch_op:
        batch_op.alter_column(
            "is_tenant_admin_flag",
            server_default=None,
        )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_tenant_admin_flag')

    # ### end Alembic commands ###
