"""Add tenant and tenant_banner models

Revision ID: e2088c7ccd81
Revises: 39559303c4a4
Create Date: 2026-02-14 00:00:46.961301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2088c7ccd81'
down_revision = '39559303c4a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'hero_theme', 
                sa.String(length=20), 
                nullable=False,
                server_default='light'
              )
          )  # Set default value for existing rows))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('hero_theme')

    # ### end Alembic commands ###
